GET http://localhost:3000/api/author

### author by id
GET http://localhost:3000/api/author/5fd59f6f80f80a0029276260

### CREATE USER

POST http://localhost:3000/api/author
Content-Type: application/json

{
  "name": "Françoase"
}

### update author
PUT http://localhost:3000/api/author/5fd59f6f80f80a0029276260
Content-Type: application/json

{
  "name": "Françoase Fogaça teste"
}

### delete author
DELETE http://localhost:3000/api/author/5fd59f6f80f80a0029276260
Content-Type: application/json
